title: Git + GitHub Workshop

collections:
  topics:
    output: true
    permalink: git-github-workshop/:name

defaults:
  - scope:
      path: ""
      type: topics
    values:
      layout: topics
